"""add language to posts

Revision ID: 119af3eb2fc7
Revises: 7620d017c755
Create Date: 2021-10-13 09:51:57.914754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119af3eb2fc7'
down_revision = '7620d017c755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
